steps:
  # Install dependencies in the functions directory
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci']
    dir: 'functions'
    
  # Build TypeScript code
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: 'functions'
    
  # Deploy to Firebase (using Firebase CLI)
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'deploy']
    dir: 'functions'
    
timeout: '1800s' # 30 minutes
options:
  logging: CLOUD_LOGGING_ONLY