steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'functions'
    args: ['ci']
    
  # Build TypeScript code
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'functions'
    args: ['run', 'build']
    
  # Deploy the function to the me-west1 region
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'functions', 
      'deploy', 
      'whatsappWebhook', 
      '--runtime', 'nodejs20', 
      '--trigger-http', 
      '--source', 'functions/', 
      '--region', 'me-west1'
    ]

timeout: '1800s'